config/routes.rb
PaperclipExample::Application.routes.draw do
  
  resources :users
  resources :tags
  resources :posters

  root 'users#index'


  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  

  mount Api::V1::Server => '/api/v1', :as => 'api_v1'
  get '/:controller(/:action(/:id))'
  post '/:controller(/:action(/:id))'
  
end

app/models/poster.rb
class Poster
	include Mongoid::Document
	include Mongoid::Timestamps

	belongs_to :user
	# has_many :tags
	has_and_belongs_to_many :tags

	field :title, type: String
	field :content, type: String
	# field :create_at, type: Integer
	# field :update_at, type: Integer
	field :user_id, type: String

	index user_id: 1
	validates :user_id, :presence => true
	validates :title, :presence => true

    # 数据验证（validation）功能:  长度限制
	validates :title, length: { maximum: 40}
	validates :content, length: { maximum: 40}

    # before_save do
        # self.activity.item.categories.each do |c|
        #     self.tags << c
        # end
    # end

	paginates_per 5

end

app/models/tag.rb
class Tag
  include Mongoid::Document

  has_and_belongs_to_many :posters

  field :name, type: String
  
  validates :name, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Sidekiq::Worker
  
  has_attached_file :avatar, 
    # :path => ":rails_root/public/system/:class/:attachement/:id/:basename_:style.:extension",
    # :url => "/system/:class/:attachement/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }


  validates_attachment :avatar,
    #:presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

  validates :name,
    :presence => true,
    :uniqueness => true
    
    
    
  def self.sidekiq_test()
      puts 'aaaaaaaaaaaaa'
  end
  
  def perform(name, count)
    puts 'Sidekiq Test!!! Doing hard work: name=' + name + ', count=' + count.to_s 
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def render_json(json = {})
	    render :text=> JSON.generate({:status => 0, :msg => "success."}.merge(json))
	end

end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :set_poster, only: [:show, :edit, :update, :destroy]

  # GET /posters
  # GET /posters.json
  def index
    #@posters = Poster.all
    #@posters = Poster.all.page(params[:page]).per(5)
    @posters = Poster.all.page(params[:page])
    @posters.each do |poster|
      poster.tags = Tag.find(poster.tag_ids)
    end

    @title = "Poster"
    
  end

  # GET /posters/1
  # GET /posters/1.json
  def show
    @tags = Tag.find(@poster.tag_ids)
  end

  # GET /posters/new
  def new
    @poster = Poster.new
    @tags = Tag.all
  end

  # GET /posters/1/edit
  def edit
    @tags = Tag.all
    @p_tags = Tag.find(@poster.tag_ids)
  end

  # POST /posters
  # POST /posters.json
  def create
    @poster = Poster.new(poster_params)
  
    respond_to do |format|
      if @poster.save
        format.html { redirect_to @poster, notice: 'Poster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poster }
      else
        format.html { render action: 'new' }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posters/1
  # PATCH/PUT /posters/1.json
  def update
    respond_to do |format|
      if @poster.update(poster_params)
        format.html { redirect_to @poster, notice: 'Poster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.json
  def destroy
    @poster.destroy
    respond_to do |format|
      format.html { redirect_to posters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poster
      @poster = Poster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poster_params
      params.require(:poster).permit(:title, :content, :create_at, :update_at, :user_id, tag_ids:[])
      # params.require(:poster).permit(:title, :content, :create_at, :update_at, :user_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @posters = Poster.find(@tag.poster_ids)
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, poster_ids:[])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new

  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :description, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posters/_form.html.erb
<%= form_for(@poster) do |f| %>
  <% if @poster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poster.errors.count, "error") %> prohibited this poster from being saved:</h2>

      <ul>
      <% @poster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <% if @tags %>
    <div class="field">
      <%= f.label :tags %>
        <% @tags.each do |tag| %>
          <% flg = 0 %> 
          <% if @p_tags %>
            <% @p_tags.each do |p_tag| %>
              <% if p_tag.id == tag.id %>            
                <% flg = 1 %> 
              <% end %> 
            <% end %> 
          <% end %> 
          <%= check_box_tag 'poster[tag_ids][]', tag.id, ('checked' if flg == 1 ) %>  
          <%= label_tag tag.name %>  
        <% end %> 
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posters/edit.html.erb
<h1>Editing poster</h1>

<%= render 'form' %>

<%= link_to 'Show', @poster %> |
<%= link_to 'Back', posters_path %>

app/views/posters/index.html.erb
<% content_for :title, @title%>

<h1>Listing posters</h1>

 <%= paginate @posters %>  

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Create at</th>
      <th>Update at</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posters.each do |poster| %>
      <tr>
        <td><%= poster.user_id %></td>
        <td><%= poster.title %></td>
        <td><%= poster.content %></td>
        <td><%= poster.created_at.to_time %></td>
        <td><%= poster.updated_at.to_time %></td>
        <td>              
            <% poster.tags.each do |tag| %>
              <%= tag.name %>&nbsp
            <% end %>
        </td>
        <!-- <td><%= poster.tags.count %></td> -->
        <td><%= link_to 'Show', poster %></td>
        <td><%= link_to 'Edit', edit_poster_path(poster) %></td>
        <td><%= link_to 'Destroy', poster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poster', new_poster_path %>

app/views/posters/new.html.erb
<h1>New poster</h1>

<%= render 'form' %>

<%= link_to 'Back', posters_path %>

app/views/posters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @poster.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @poster.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poster.content %>
</p>

<p>
  <strong>Create at:</strong>
  <%= @poster.created_at.to_time %>
</p>

<p>
  <strong>Update at:</strong>
  <%= @poster.updated_at.to_time %>
</p>

<p>
  <strong>Tags:</strong>
    <% @tags.each do |tag| %>
      <%= tag.name %>&nbsp
    <% end %> 
</p>

<%= link_to 'Edit', edit_poster_path(@poster) %> |
<%= link_to 'Back', posters_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Poster List:</strong><br>
    <% @posters.each do |poster| %>
      <%= poster.title %> <br> 
    <% end %> 
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/_fxrm.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'fxrm' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb) %></td>
        <td><%= user.name %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'fxrm' %>


<input type="button" value="Create User with Sinatra API" id="hello"></input>
<br>
<script language="javascript">
(function() {
  $(document).ready(function() {
    return $('#hello').bind('click', function() {
        if(!$('#user_name').val()){
          alert("Name is null");
          return false;
        }
        $.ajax({
          url: '/api/v1/users/create',
          type: "post",
          data: $("#new_user").serialize(),
          cache: false,
          dataType: 'json',
          timeout: 10000,
          success: function(data, textStatus){
            location.href="/users/"+data['id']
          }
        });
      return;
    });
  });

}).call(this);
</script>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong >Name:</strong>
  <label id="user_id"><%= @user.name %></label>

</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>



<p>
  <strong>Avatar:</strong>
  <%= image_tag @user.avatar.url(:large) %>
</p>

<input type="button" value="Poster List Get" id="poster_get"></input>

<div style="display: none;" id="poster_pagination">
<!--   <span id="page_first"> <a href="/api/v1/user/posters?page=1" rel="prev">« First </a> </span>
  <span id="page_first"> <a href="/api/v1/user/posters?page=1" rel="prev">‹ Prev</a>
  <span id="page_next"> <a href="/api/v1/user/posters?page=2" rel="next">Next ›</a> </span>
  <span id="page_last"> <a href="/api/v1/user/posters?page=2">Last »</a> </span>

  <span id="page_view"></span> <br>
  <span id="page_first"> « First </span>
  <span id="page_prev"> ‹ Prev</span>
  <span id="page_next"> Next ›</span>
  <span id="page_last"> Last »</span>
-->  
  <span id="page_view"></span> <br>
  <span id="page_first"> <u>« First </u></span>
  <span id="page_prev"> <u>‹ Prev</u></span>
  <span id="page_next"> <u>Next ›</u></span>
  <span id="page_last"> <u>Last »</u></span>
</div>


<!-- <div id ="prev"> prev</div><div id ="next"> next</div> -->
<table id="poster_list"></table>  
<br>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<script language="javascript">
(function() {
  $(document).ready(function() {
    $('#poster_get').bind('click', function() {  

        var data = "id=" + $("#user_id").text() + "&limit=5";
         $.ajax({
           url: '/api/v1/user/posters',
           type: "post",
           data: data,
           cache: false,
           dataType: 'json',
           timeout: 10000,
           success: function(data, textStatus){

            var dx = data.posters;
            if(dx && dx.length)
            {
              var tb = $('#poster_list');
              var tb_str = "<thead><tr><td>Title</td><td>Content</td></tr></thead><tbody>";
              for(var i=0; i<dx.length; i++)
              {
                tb_str += "<tr><td>" + dx[i]['title'] + "</td><td>" +  dx[i]['content'] + "</td></tr>";
              } 
              tb_str += "</tbody>";

              var limit = 5;
              if (data.len > limit)
              {
                var page = Math.ceil(data.len / limit);
                $('#page_view').text("Page: 1/" + page);
                $('#page_view').attr("total", page);
                $('#page_view').attr("curr", 1);
                document.getElementById("poster_pagination").style.display="";  
              }
                   
              tb.empty().append(tb_str);              
                
            }
            else
            {
              $('#poster_get').after("<span style=\"font-size:12px;color:#FF0000;\">No Poster!</span>");
            }
           }
         });
    });

    $('#page_first').bind('click', function() {  
        var curr = $('#page_view').attr("curr");
        if (curr == 1)
        {
          alert("Already the first page!");
          return;
        }
        
        var data = "id=" + $("#user_id").text() + "&limit=5&page=1";
         $.ajax({
           url: '/api/v1/user/posters',
           type: "post",
           data: data,
           cache: false,
           dataType: 'json',
           timeout: 10000,
           success: function(data, textStatus){

            var dx = data.posters;
            if(dx && dx.length)
            {
              var tb = $('#poster_list');
              var tb_str = "<thead><tr><td>Title</td><td>Content</td></tr></thead><tbody>";
              for(var i=0; i<dx.length; i++)
              {
                tb_str += "<tr><td>" + dx[i]['title'] + "</td><td>" +  dx[i]['content'] + "</td></tr>";
              } 
              tb_str += "</tbody>";

              $('#page_view').text("Page: 1/" + $('#page_view').attr("total"));
              $('#page_view').attr("curr", 1);                   
              tb.empty().append(tb_str);              
                
            }
           }
         });
    });

    $('#page_prev').bind('click', function() {  
        var curr = $('#page_view').attr("curr");
        if (curr == 1)
        {
          alert("Already the first page!");
          return;
        }

        curr -= 1;
        var data = "id=" + $("#user_id").text() + "&limit=5&page=" + curr;        
        $.ajax({
           url: '/api/v1/user/posters',
           type: "post",
           data: data,
           cache: false,
           dataType: 'json',
           timeout: 10000,
           success: function(data, textStatus){

            var dx = data.posters;
            if(dx && dx.length)
            {
              var tb = $('#poster_list');
              var tb_str = "<thead><tr><td>Title</td><td>Content</td></tr></thead><tbody>";
              for(var i=0; i<dx.length; i++)
              {
                tb_str += "<tr><td>" + dx[i]['title'] + "</td><td>" +  dx[i]['content'] + "</td></tr>";
              } 
              tb_str += "</tbody>";

              $('#page_view').text("Page: " + curr + "/" + $('#page_view').attr("total"));
              $('#page_view').attr("curr", curr);          
              tb.empty().append(tb_str); 
                
            }
           }
         });
    });

    $('#page_next').bind('click', function() { 
        var curr = parseInt($('#page_view').attr("curr"));
        var total = parseInt($('#page_view').attr("total"));
        if (curr == total)
        {
          alert("Already the last page!");
          return;
        }

        curr += 1; 
        
        var data = "id=" + $("#user_id").text() + "&limit=5&page=" + curr;
        $.ajax({
           url: '/api/v1/user/posters',
           type: "post",
           data: data,
           cache: false,
           dataType: 'json',
           timeout: 10000,
           success: function(data, textStatus){

            var dx = data.posters;
            if(dx && dx.length)
            {
              var tb = $('#poster_list');
              var tb_str = "<thead><tr><td>Title</td><td>Content</td></tr></thead><tbody>";
              for(var i=0; i<dx.length; i++){
                tb_str += "<tr><td>" + dx[i]['title'] + "</td><td>" +  dx[i]['content'] + "</td></tr>";
              } 
              tb_str += "</tbody>";

              $('#page_view').text("Page: " + curr + "/" + total);
              $('#page_view').attr("curr", curr);          
              tb.empty().append(tb_str);               
                
            }
           }
         });
    });

    $('#page_last').bind('click', function() {  
        var curr = parseInt($('#page_view').attr("curr"));
        var total = parseInt($('#page_view').attr("total"));
        if (curr == total)
        {
          alert("Already the last page!");
          return;
        }

        var data = "id=" + $("#user_id").text() + "&limit=5&page=" + total;
         $.ajax({
           url: '/api/v1/user/posters',
           type: "post",
           data: data,
           cache: false,
           dataType: 'json',
           timeout: 10000,
           success: function(data, textStatus){

            var dx = data.posters;          
            if(dx && dx.length)
            {
              var tb = $('#poster_list');
              var tb_str = "<thead><tr><td>Title</td><td>Content</td></tr></thead><tbody>";
              for(var i=0; i<dx.length; i++)
              {
                tb_str += "<tr><td>" + dx[i]['title'] + "</td><td>" +  dx[i]['content'] + "</td></tr>";
              } 
              tb_str += "</tbody>";
              $('#page_view').text("Page: " + total + "/" + total);
              $('#page_view').attr("curr", total);          
              tb.empty().append(tb_str);              
                
            }
           }
         });
    });

  });

}).call(this);
</script>